query Sets($pID:ID!,$tournamentList:[ID],$perPage:Int,$page:Int) {
  player(id: $pID) {
    id
    sets(perPage: $perPage, page: $page, filters:{eventIds: $tournamentList, state: [2]}) {
      pageInfo {
        total
        filter
        totalPages
      }
      nodes {
	id
        completedAt
        identifier
        startAt
        state
        stream {
          id
          enabled
          isOnline
          parentStreamId
          streamId
          streamLogo
          streamName
          streamType
          streamSource
          streamType
          streamTypeId
          streamStatus
          numSetups
        }
        event {
          name
          slug
          startAt
	}
        slots(includeByes: false) {
	  entrant {
            id
            name
            participants {
              player {
	        id
                user {
                  id
                }
              }
            }
          }
        }
        games {
          id
          selections {
            selectionType
            selectionValue
            entrant {
              id
              name
              participants {
                player {
                  gamerTag
                  id
                }
              }
            }
          }
        }
        vodUrl
        winnerId
        fullRoundText
        wPlacement
        lPlacement
        displayScore
      }
    }
  }
}
